name: Build iOS app

on:
  push:
    branches:
      - kotlin-toolchain
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    # Only run build in template repo
    if: github.event.repository.name == 'KMP-App-Template' && github.repository_owner == 'Kotlin'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.3.app/Contents/Developer
      - name: iOS debug build
        run: ./kotlin build -m iosApp -p iosSimulatorArm64 -v debug
